package com.example.kanjimemorized

import javax.inject.Singleton

data class SimpleIdeogram(
    val unicode: String,
    val meanings: List<String>,
    val strokes: Int
)

object IdeogramData {
    @Singleton
    val radicalIdeogramData: Array<SimpleIdeogram> = arrayOf(
        SimpleIdeogram(unicode = "2F00", meanings = listOf("one"), strokes = 1),
        SimpleIdeogram(unicode = "2F01", meanings = listOf("line"), strokes = 1),
        SimpleIdeogram(unicode = "2F02", meanings = listOf("dot"), strokes = 1),
        SimpleIdeogram(unicode = "2F03", meanings = listOf("slash"), strokes = 1),
        SimpleIdeogram(unicode = "2F04", meanings = listOf("second"), strokes = 1),
        SimpleIdeogram(unicode = "2F05", meanings = listOf("hook"), strokes = 1),
        SimpleIdeogram(unicode = "2F06", meanings = listOf("two"), strokes = 2),
        SimpleIdeogram(unicode = "2F07", meanings = listOf("lid"), strokes = 2),
        SimpleIdeogram(unicode = "2F08", meanings = listOf("man"), strokes = 2),
        SimpleIdeogram(unicode = "2F09", meanings = listOf("legs"), strokes = 2),
        SimpleIdeogram(unicode = "2F0A", meanings = listOf("enter"), strokes = 2),
        SimpleIdeogram(unicode = "2F0B", meanings = listOf("eight"), strokes = 2),
        SimpleIdeogram(unicode = "2F0C", meanings = listOf("down box"), strokes = 2),
        SimpleIdeogram(unicode = "2F0D", meanings = listOf("cover"), strokes = 2),
        SimpleIdeogram(unicode = "2F0E", meanings = listOf("ice"), strokes = 2),
        SimpleIdeogram(unicode = "2F0F", meanings = listOf("table"), strokes = 2),

        SimpleIdeogram(unicode = "2F10", meanings = listOf("open box"), strokes = 2),
        SimpleIdeogram(unicode = "2F11", meanings = listOf("knife"), strokes = 2),
        SimpleIdeogram(unicode = "2F12", meanings = listOf("power"), strokes = 2),
        SimpleIdeogram(unicode = "2F13", meanings = listOf("wrap"), strokes = 2),
        SimpleIdeogram(unicode = "2F14", meanings = listOf("spoon"), strokes = 2),
        SimpleIdeogram(unicode = "2F15", meanings = listOf("right open box"), strokes = 2),
        SimpleIdeogram(unicode = "2F16", meanings = listOf("hiding enclosure"), strokes = 2),
        SimpleIdeogram(unicode = "2F17", meanings = listOf("ten"), strokes = 2),
        SimpleIdeogram(unicode = "2F18", meanings = listOf("divination"), strokes = 2),
        SimpleIdeogram(unicode = "2F19", meanings = listOf("seal"), strokes = 2),
        SimpleIdeogram(unicode = "2F1A", meanings = listOf("cliff"), strokes = 2),
        SimpleIdeogram(unicode = "2F1B", meanings = listOf("private"), strokes = 2),
        SimpleIdeogram(unicode = "2F1C", meanings = listOf("again"), strokes = 2),
        SimpleIdeogram(unicode = "2F1D", meanings = listOf("mouth"), strokes = 3),
        SimpleIdeogram(unicode = "2F1E", meanings = listOf("enclosure"), strokes = 3),
        SimpleIdeogram(unicode = "2F1F", meanings = listOf("earth"), strokes = 3),

        SimpleIdeogram(unicode = "2F20", meanings = listOf("scholar"), strokes = 3),
        SimpleIdeogram(unicode = "2F21", meanings = listOf("go"), strokes = 3),
        SimpleIdeogram(unicode = "2F22", meanings = listOf("go slowly"), strokes = 3),
        SimpleIdeogram(unicode = "2F23", meanings = listOf("evening"), strokes = 3),
        SimpleIdeogram(unicode = "2F24", meanings = listOf("big"), strokes = 3),
        SimpleIdeogram(unicode = "2F25", meanings = listOf("woman"), strokes = 3),
        SimpleIdeogram(unicode = "2F26", meanings = listOf("child"), strokes = 3),
        SimpleIdeogram(unicode = "2F27", meanings = listOf("roof"), strokes = 3),
        SimpleIdeogram(unicode = "2F28", meanings = listOf("inch"), strokes = 3),
        SimpleIdeogram(unicode = "2F29", meanings = listOf("small"), strokes = 3),
        SimpleIdeogram(unicode = "2F2A", meanings = listOf("lame"), strokes = 3),
        SimpleIdeogram(unicode = "2F2B", meanings = listOf("corpse"), strokes = 3),
        SimpleIdeogram(unicode = "2F2C", meanings = listOf("sprout"), strokes = 3),
        SimpleIdeogram(unicode = "2F2D", meanings = listOf("mountain"), strokes = 3),
        SimpleIdeogram(unicode = "2F2E", meanings = listOf("river"), strokes = 3),
        SimpleIdeogram(unicode = "2F2F", meanings = listOf("work"), strokes = 3),

        SimpleIdeogram(unicode = "2F30", meanings = listOf("oneself"), strokes = 3),
        SimpleIdeogram(unicode = "2F31", meanings = listOf("turban"), strokes = 3),
        SimpleIdeogram(unicode = "2F32", meanings = listOf("dry"), strokes = 3),
        SimpleIdeogram(unicode = "2F33", meanings = listOf("short thread"), strokes = 3),
        SimpleIdeogram(unicode = "2F34", meanings = listOf("dotted cliff"), strokes = 3),
        SimpleIdeogram(unicode = "2F35", meanings = listOf("long stride"), strokes = 3),
        SimpleIdeogram(unicode = "2F36", meanings = listOf("two hands"), strokes = 3),
        SimpleIdeogram(unicode = "2F37", meanings = listOf("shoot"), strokes = 3),
        SimpleIdeogram(unicode = "2F38", meanings = listOf("bow"), strokes = 3),
        SimpleIdeogram(unicode = "2F39", meanings = listOf("snout"), strokes = 3),
        SimpleIdeogram(unicode = "2F3A", meanings = listOf("bristle"), strokes = 3),
        SimpleIdeogram(unicode = "2F3B", meanings = listOf("step"), strokes = 3),
        SimpleIdeogram(unicode = "2F3C", meanings = listOf("heart"), strokes = 4),
        SimpleIdeogram(unicode = "2F3D", meanings = listOf("halberd"), strokes = 4),
        SimpleIdeogram(unicode = "2F3E", meanings = listOf("door"), strokes = 4),
        SimpleIdeogram(unicode = "2F3F", meanings = listOf("hand"), strokes = 4),

        SimpleIdeogram(unicode = "2F40", meanings = listOf("branch"), strokes = 4),
        SimpleIdeogram(unicode = "2F41", meanings = listOf("rap"), strokes = 4),
        SimpleIdeogram(unicode = "2F42", meanings = listOf("script"), strokes = 4),
        SimpleIdeogram(unicode = "2F43", meanings = listOf("dipper"), strokes = 4),
        SimpleIdeogram(unicode = "2F44", meanings = listOf("axe"), strokes = 4),
        SimpleIdeogram(unicode = "2F45", meanings = listOf("square"), strokes = 4),
        SimpleIdeogram(unicode = "2F46", meanings = listOf("not"), strokes = 4),
        SimpleIdeogram(unicode = "2F47", meanings = listOf("sun"), strokes = 4),
        SimpleIdeogram(unicode = "2F48", meanings = listOf("say"), strokes = 4),
        SimpleIdeogram(unicode = "2F49", meanings = listOf("moon"), strokes = 4),
        SimpleIdeogram(unicode = "2F4A", meanings = listOf("tree"), strokes = 4),
        SimpleIdeogram(unicode = "2F4B", meanings = listOf("lack"), strokes = 4),
        SimpleIdeogram(unicode = "2F4C", meanings = listOf("stop"), strokes = 4),
        SimpleIdeogram(unicode = "2F4D", meanings = listOf("death"), strokes = 4),
        SimpleIdeogram(unicode = "2F4E", meanings = listOf("weapon"), strokes = 4),
        SimpleIdeogram(unicode = "2F4F", meanings = listOf("do not"), strokes = 4),

        SimpleIdeogram(unicode = "2F50", meanings = listOf("compare"), strokes = 4),
        SimpleIdeogram(unicode = "2F51", meanings = listOf("fur"), strokes = 4),
        SimpleIdeogram(unicode = "2F52", meanings = listOf("clan"), strokes = 4),
        SimpleIdeogram(unicode = "2F53", meanings = listOf("steam"), strokes = 4),
        SimpleIdeogram(unicode = "2F54", meanings = listOf("water"), strokes = 4),
        SimpleIdeogram(unicode = "2F55", meanings = listOf("fire"), strokes = 4),
        SimpleIdeogram(unicode = "2F56", meanings = listOf("claw"), strokes = 4),
        SimpleIdeogram(unicode = "2F57", meanings = listOf("father"), strokes = 4),
        SimpleIdeogram(unicode = "2F58", meanings = listOf("double x"), strokes = 4),
        SimpleIdeogram(unicode = "2F59", meanings = listOf("half tree trunk"), strokes = 4),
        SimpleIdeogram(unicode = "2F5A", meanings = listOf("slice"), strokes = 4),
        SimpleIdeogram(unicode = "2F5B", meanings = listOf("fang"), strokes = 4),
        SimpleIdeogram(unicode = "2F5C", meanings = listOf("cow"), strokes = 4),
        SimpleIdeogram(unicode = "2F5D", meanings = listOf("dog"), strokes = 4),
        SimpleIdeogram(unicode = "2F5E", meanings = listOf("profound"), strokes = 5),
        SimpleIdeogram(unicode = "2F5F", meanings = listOf("jade"), strokes = 4),

        SimpleIdeogram(unicode = "2F60", meanings = listOf("melon"), strokes = 6),
        SimpleIdeogram(unicode = "2F61", meanings = listOf("tile"), strokes = 5),
        SimpleIdeogram(unicode = "2F62", meanings = listOf("sweet"), strokes = 5),
        SimpleIdeogram(unicode = "2F63", meanings = listOf("life"), strokes = 5),
        SimpleIdeogram(unicode = "2F64", meanings = listOf("use"), strokes = 5),
        SimpleIdeogram(unicode = "2F65", meanings = listOf("field"), strokes = 5),
        SimpleIdeogram(unicode = "2F66", meanings = listOf("bolt of cloth"), strokes = 5),
        SimpleIdeogram(unicode = "2F67", meanings = listOf("sickness"), strokes = 5),
        SimpleIdeogram(unicode = "2F68", meanings = listOf("dotted tent"), strokes = 5),
        SimpleIdeogram(unicode = "2F69", meanings = listOf("white"), strokes = 5),
        SimpleIdeogram(unicode = "2F6A", meanings = listOf("skin"), strokes = 5),
        SimpleIdeogram(unicode = "2F6B", meanings = listOf("dish"), strokes = 5),
        SimpleIdeogram(unicode = "2F6C", meanings = listOf("eye"), strokes = 5),
        SimpleIdeogram(unicode = "2F6D", meanings = listOf("spear"), strokes = 5),
        SimpleIdeogram(unicode = "2F6E", meanings = listOf("arrow"), strokes = 5),
        SimpleIdeogram(unicode = "2F6F", meanings = listOf("stone"), strokes = 5),

        SimpleIdeogram(unicode = "2F70", meanings = listOf("spirit"), strokes = 5),
        SimpleIdeogram(unicode = "2F71", meanings = listOf("track"), strokes = 5),
        SimpleIdeogram(unicode = "2F72", meanings = listOf("grain"), strokes = 5),
        SimpleIdeogram(unicode = "2F73", meanings = listOf("cave"), strokes = 5),
        SimpleIdeogram(unicode = "2F74", meanings = listOf("stand"), strokes = 5),
        SimpleIdeogram(unicode = "2F75", meanings = listOf("bamboo"), strokes = 6),
        SimpleIdeogram(unicode = "2F76", meanings = listOf("rice"), strokes = 6),
        SimpleIdeogram(unicode = "2F77", meanings = listOf("silk"), strokes = 6),
        SimpleIdeogram(unicode = "2F78", meanings = listOf("jar"), strokes = 6),
        SimpleIdeogram(unicode = "2F79", meanings = listOf("net"), strokes = 6),
        SimpleIdeogram(unicode = "2F7A", meanings = listOf("sheep"), strokes = 6),
        SimpleIdeogram(unicode = "2F7B", meanings = listOf("feather"), strokes = 6),
        SimpleIdeogram(unicode = "2F7C", meanings = listOf("old"), strokes = 6),
        SimpleIdeogram(unicode = "2F7D", meanings = listOf("and"), strokes = 6),
        SimpleIdeogram(unicode = "2F7E", meanings = listOf("plow"), strokes = 6),
        SimpleIdeogram(unicode = "2F7F", meanings = listOf("ear"), strokes = 6),

        SimpleIdeogram(unicode = "2F80", meanings = listOf("brush"), strokes = 6),
        SimpleIdeogram(unicode = "2F81", meanings = listOf("meat"), strokes = 6),
        SimpleIdeogram(unicode = "2F82", meanings = listOf("minister"), strokes = 7),
        SimpleIdeogram(unicode = "2F83", meanings = listOf("self"), strokes = 6),
        SimpleIdeogram(unicode = "2F84", meanings = listOf("arrive"), strokes = 6),
        SimpleIdeogram(unicode = "2F85", meanings = listOf("mortar"), strokes = 6),
        SimpleIdeogram(unicode = "2F86", meanings = listOf("tongue"), strokes = 6),
        SimpleIdeogram(unicode = "2F87", meanings = listOf("oppose"), strokes = 6),
        SimpleIdeogram(unicode = "2F88", meanings = listOf("boat"), strokes = 6),
        SimpleIdeogram(unicode = "2F89", meanings = listOf("stopping"), strokes = 6),
        SimpleIdeogram(unicode = "2F8A", meanings = listOf("color"), strokes = 6),
        SimpleIdeogram(unicode = "2F8B", meanings = listOf("grass"), strokes = 6),
        SimpleIdeogram(unicode = "2F8C", meanings = listOf("tiger"), strokes = 6),
        SimpleIdeogram(unicode = "2F8D", meanings = listOf("insect"), strokes = 6),
        SimpleIdeogram(unicode = "2F8E", meanings = listOf("blood"), strokes = 6),
        SimpleIdeogram(unicode = "2F8F", meanings = listOf("walk enclosure"), strokes = 6),

        SimpleIdeogram(unicode = "2F90", meanings = listOf("clothes"), strokes = 6),
        SimpleIdeogram(unicode = "2F91", meanings = listOf("west"), strokes = 6),
        SimpleIdeogram(unicode = "2F92", meanings = listOf("see"), strokes = 7),
        SimpleIdeogram(unicode = "2F93", meanings = listOf("horn"), strokes = 7),
        SimpleIdeogram(unicode = "2F94", meanings = listOf("speech"), strokes = 7),
        SimpleIdeogram(unicode = "2F95", meanings = listOf("valley"), strokes = 7),
        SimpleIdeogram(unicode = "2F96", meanings = listOf("bean"), strokes = 7),
        SimpleIdeogram(unicode = "2F97", meanings = listOf("pig"), strokes = 7),
        SimpleIdeogram(unicode = "2F98", meanings = listOf("badger"), strokes = 7),
        SimpleIdeogram(unicode = "2F99", meanings = listOf("shell"), strokes = 7),
        SimpleIdeogram(unicode = "2F9A", meanings = listOf("red"), strokes = 7),
        SimpleIdeogram(unicode = "2F9B", meanings = listOf("run"), strokes = 7),
        SimpleIdeogram(unicode = "2F9C", meanings = listOf("foot"), strokes = 7),
        SimpleIdeogram(unicode = "2F9D", meanings = listOf("body"), strokes = 7),
        SimpleIdeogram(unicode = "2F9E", meanings = listOf("cart"), strokes = 7),
        SimpleIdeogram(unicode = "2F9F", meanings = listOf("bitter"), strokes = 7),

        SimpleIdeogram(unicode = "2FA0", meanings = listOf("morning"), strokes = 7),
        SimpleIdeogram(unicode = "2FA1", meanings = listOf("walk"), strokes = 3),
        SimpleIdeogram(unicode = "2FA2", meanings = listOf("city"), strokes = 7),
        SimpleIdeogram(unicode = "2FA3", meanings = listOf("wine"), strokes = 7),
        SimpleIdeogram(unicode = "2FA4", meanings = listOf("distinguish"), strokes = 7),
        SimpleIdeogram(unicode = "2FA5", meanings = listOf("village"), strokes = 7),
        SimpleIdeogram(unicode = "2FA6", meanings = listOf("gold"), strokes = 8),
        SimpleIdeogram(unicode = "2FA7", meanings = listOf("long"), strokes = 8),
        SimpleIdeogram(unicode = "2FA8", meanings = listOf("gate"), strokes = 8),
        SimpleIdeogram(unicode = "2FA9", meanings = listOf("mound"), strokes = 3),
        SimpleIdeogram(unicode = "2FAA", meanings = listOf("slave"), strokes = 8),
        SimpleIdeogram(unicode = "2FAB", meanings = listOf("short tailed bird"), strokes = 8),
        SimpleIdeogram(unicode = "2FAC", meanings = listOf("rain"), strokes = 8),
        SimpleIdeogram(unicode = "2FAD", meanings = listOf("blue"), strokes = 8),
        SimpleIdeogram(unicode = "2FAE", meanings = listOf("wrong"), strokes = 8),
        SimpleIdeogram(unicode = "2FAF", meanings = listOf("face"), strokes = 9),

        SimpleIdeogram(unicode = "2FB0", meanings = listOf("leather"), strokes = 9),
        SimpleIdeogram(unicode = "2FB1", meanings = listOf("tanned leather"), strokes = 10),
        SimpleIdeogram(unicode = "2FB2", meanings = listOf("leek"), strokes = 9),
        SimpleIdeogram(unicode = "2FB3", meanings = listOf("sound"), strokes = 9),
        SimpleIdeogram(unicode = "2FB4", meanings = listOf("leaf"), strokes = 9),
        SimpleIdeogram(unicode = "2FB5", meanings = listOf("wind"), strokes = 9),
        SimpleIdeogram(unicode = "2FB6", meanings = listOf("fly"), strokes = 9),
        SimpleIdeogram(unicode = "2FB7", meanings = listOf("eat"), strokes = 9),
        SimpleIdeogram(unicode = "2FB8", meanings = listOf("head"), strokes = 9),
        SimpleIdeogram(unicode = "2FB9", meanings = listOf("fragrant"), strokes = 9),
        SimpleIdeogram(unicode = "2FBA", meanings = listOf("horse"), strokes = 10),
        SimpleIdeogram(unicode = "2FBB", meanings = listOf("bone"), strokes = 10),
        SimpleIdeogram(unicode = "2FBC", meanings = listOf("tall"), strokes = 10),
        SimpleIdeogram(unicode = "2FBD", meanings = listOf("hair"), strokes = 10),
        SimpleIdeogram(unicode = "2FBE", meanings = listOf("fight"), strokes = 10),
        SimpleIdeogram(unicode = "2FBF", meanings = listOf("sacrificial wine"), strokes = 10),

        SimpleIdeogram(unicode = "2FC0", meanings = listOf("cauldron"), strokes = 10),
        SimpleIdeogram(unicode = "2FC1", meanings = listOf("ghost"), strokes = 10),
        SimpleIdeogram(unicode = "2FC2", meanings = listOf("fish"), strokes = 11),
        SimpleIdeogram(unicode = "2FC3", meanings = listOf("bird"), strokes = 11),
        SimpleIdeogram(unicode = "2FC4", meanings = listOf("salt"), strokes = 11),
        SimpleIdeogram(unicode = "2FC5", meanings = listOf("deer"), strokes = 11),
        SimpleIdeogram(unicode = "2FC6", meanings = listOf("wheat"), strokes = 11),
        SimpleIdeogram(unicode = "2FC7", meanings = listOf("hemp"), strokes = 11),
        SimpleIdeogram(unicode = "2FC8", meanings = listOf("yellow"), strokes = 12),
        SimpleIdeogram(unicode = "2FC9", meanings = listOf("millet"), strokes = 12),
        SimpleIdeogram(unicode = "2FCA", meanings = listOf("black"), strokes = 12),
        SimpleIdeogram(unicode = "2FCB", meanings = listOf("embroidery"), strokes = 12),
        SimpleIdeogram(unicode = "2FCC", meanings = listOf("frog"), strokes = 13),
        SimpleIdeogram(unicode = "2FCD", meanings = listOf("tripod"), strokes = 13),
        SimpleIdeogram(unicode = "2FCE", meanings = listOf("drum"), strokes = 13),
        SimpleIdeogram(unicode = "2FCF", meanings = listOf("rat"), strokes = 13),

        SimpleIdeogram(unicode = "2FD0", meanings = listOf("nose"), strokes = 14),
        SimpleIdeogram(unicode = "2FD1", meanings = listOf("even"), strokes = 14),
        SimpleIdeogram(unicode = "2FD2", meanings = listOf("tooth"), strokes = 15),
        SimpleIdeogram(unicode = "2FD3", meanings = listOf("dragon"), strokes = 16),
        SimpleIdeogram(unicode = "2FD4", meanings = listOf("turtle"), strokes = 16),
        SimpleIdeogram(unicode = "2FD5", meanings = listOf("flute"), strokes = 17),
        )
}