package com.example.kanjimemorized

import com.example.kanjimemorized.data.Ideogram
import javax.inject.Singleton

object IdeogramData {
    @Singleton
    val radicalIdeogramData: Array<Ideogram> = arrayOf(
/*https://www.kanjidamage.com/kanji*/
        Ideogram(unicode = '\u2F00', meanings = listOf("one"), strokes = 1),
        Ideogram(unicode = '\u2F01', meanings = listOf("line"), strokes = 1),
        Ideogram(unicode = '\u2F02', meanings = listOf("dot"), strokes = 1),
        Ideogram(unicode = '\u2F03', meanings = listOf("slash"), strokes = 1),
        Ideogram(unicode = '\u2F04', meanings = listOf("second"), strokes = 1),
        Ideogram(unicode = '\u2F05', meanings = listOf("hook"), strokes = 1),
        Ideogram(unicode = '\u2F06', meanings = listOf("two"), strokes = 2, decompositions = listOf('\u2F00')),
        Ideogram(unicode = '\u2F07', meanings = listOf("lid"), strokes = 2),
        Ideogram(unicode = '\u2F08', meanings = listOf("man", "person"), strokes = 2),
        Ideogram(unicode = '\u2F09', meanings = listOf("legs"), strokes = 2, decompositions = listOf('\u2F03')),
        Ideogram(unicode = '\u2F0A', meanings = listOf("enter"), strokes = 2),
        Ideogram(unicode = '\u2F0B', meanings = listOf("eight"), strokes = 2),
        Ideogram(unicode = '\u2F0C', meanings = listOf("down box", "to enclose"), strokes = 2),
        Ideogram(unicode = '\u2F0D', meanings = listOf("cover", "crown"), strokes = 2),
        Ideogram(unicode = '\u2F0E', meanings = listOf("ice"), strokes = 2, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F0F', meanings = listOf("table"), strokes = 2),

        Ideogram(unicode = '\u2F10', meanings = listOf("open box", "container"), strokes = 2),
        Ideogram(unicode = '\u2F11', meanings = listOf("knife"), strokes = 2),
        Ideogram(unicode = '\u2F12', meanings = listOf("power"), strokes = 2),
        Ideogram(unicode = '\u2F13', meanings = listOf("wrap"), strokes = 2),
        Ideogram(unicode = '\u2F14', meanings = listOf("spoon"), strokes = 2),
        Ideogram(unicode = '\u2F15', meanings = listOf("right open box"), strokes = 2),
        Ideogram(unicode = '\u2F16', meanings = listOf("hiding enclosure"), strokes = 2),
        Ideogram(unicode = '\u2F17', meanings = listOf("ten"), strokes = 2),
        Ideogram(unicode = '\u2F18', meanings = listOf("divination", "oracle"), strokes = 2, decompositions = listOf('\u2F01', '\u2F02')),
        Ideogram(unicode = '\u2F19', meanings = listOf("seal"), strokes = 2),
        Ideogram(unicode = '\u2F1A', meanings = listOf("cliff"), strokes = 2),
        Ideogram(unicode = '\u2F1B', meanings = listOf("private"), strokes = 2),
        Ideogram(unicode = '\u2F1C', meanings = listOf("again"), strokes = 2),
        Ideogram(unicode = '\u2F1D', meanings = listOf("mouth"), strokes = 3),
        Ideogram(unicode = '\u2F1E', meanings = listOf("enclosure"), strokes = 3),
        Ideogram(unicode = '\u2F1F', meanings = listOf("earth"), strokes = 3),

        Ideogram(unicode = '\u2F20', meanings = listOf("scholar", "samurai"), strokes = 3),
        Ideogram(unicode = '\u2F21', meanings = listOf("go", "follow"), strokes = 3),
        Ideogram(unicode = '\u2F22', meanings = listOf("go slowly"), strokes = 3),
        Ideogram(unicode = '\u2F23', meanings = listOf("evening"), strokes = 3),
        Ideogram(unicode = '\u2F24', meanings = listOf("big"), strokes = 3),
        Ideogram(unicode = '\u2F25', meanings = listOf("woman"), strokes = 3),
        Ideogram(unicode = '\u2F26', meanings = listOf("child"), strokes = 3),
        Ideogram(unicode = '\u2F27', meanings = listOf("roof"), strokes = 3),
        Ideogram(unicode = '\u2F28', meanings = listOf("inch"), strokes = 3, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F29', meanings = listOf("small"), strokes = 3, decompositions = listOf('\u2F02', '\u2F05')),
        Ideogram(unicode = '\u2F2A', meanings = listOf("lame"), strokes = 3),
        Ideogram(unicode = '\u2F2B', meanings = listOf("corpse"), strokes = 3),
        Ideogram(unicode = '\u2F2C', meanings = listOf("sprout"), strokes = 3),
        Ideogram(unicode = '\u2F2D', meanings = listOf("mountain"), strokes = 3),
        Ideogram(unicode = '\u2F2E', meanings = listOf("river"), strokes = 3),
        Ideogram(unicode = '\u2F2F', meanings = listOf("work"), strokes = 3),

        Ideogram(unicode = '\u2F30', meanings = listOf("oneself"), strokes = 3),
        Ideogram(unicode = '\u2F31', meanings = listOf("turban"), strokes = 3),
        Ideogram(unicode = '\u2F32', meanings = listOf("dry"), strokes = 3),
        Ideogram(unicode = '\u2F33', meanings = listOf("short thread"), strokes = 3),
        Ideogram(unicode = '\u2F34', meanings = listOf("dotted cliff"), strokes = 3),
        Ideogram(unicode = '\u2F35', meanings = listOf("long stride"), strokes = 3),
        Ideogram(unicode = '\u2F36', meanings = listOf("two hands"), strokes = 3),
        Ideogram(unicode = '\u2F37', meanings = listOf("shoot"), strokes = 3, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F38', meanings = listOf("bow"), strokes = 3),
        Ideogram(unicode = '\u2F39', meanings = listOf("snout"), strokes = 3),
        Ideogram(unicode = '\u2F3A', meanings = listOf("bristle"), strokes = 3),
        Ideogram(unicode = '\u2F3B', meanings = listOf("step"), strokes = 3),
        Ideogram(unicode = '\u2F3C', meanings = listOf("heart"), strokes = 4, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F3D', meanings = listOf("halberd"), strokes = 4, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F3E', meanings = listOf("door"), strokes = 4),
        Ideogram(unicode = '\u2F3F', meanings = listOf("hand"), strokes = 4),

        Ideogram(unicode = '\u2F40', meanings = listOf("branch"), strokes = 4),
        Ideogram(unicode = '\u2F41', meanings = listOf("rap"), strokes = 4),
        Ideogram(unicode = '\u2F42', meanings = listOf("script"), strokes = 4),
        Ideogram(unicode = '\u2F43', meanings = listOf("dipper"), strokes = 4, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F44', meanings = listOf("axe"), strokes = 4),
        Ideogram(unicode = '\u2F45', meanings = listOf("square"), strokes = 4),
        Ideogram(unicode = '\u2F46', meanings = listOf("not"), strokes = 4),
        Ideogram(unicode = '\u2F47', meanings = listOf("sun"), strokes = 4),
        Ideogram(unicode = '\u2F48', meanings = listOf("say"), strokes = 4),
        Ideogram(unicode = '\u2F49', meanings = listOf("moon"), strokes = 4),
        Ideogram(unicode = '\u2F4A', meanings = listOf("tree"), strokes = 4),
        Ideogram(unicode = '\u2F4B', meanings = listOf("lack"), strokes = 4),
        Ideogram(unicode = '\u2F4C', meanings = listOf("stop"), strokes = 4),
        Ideogram(unicode = '\u2F4D', meanings = listOf("death"), strokes = 4),
        Ideogram(unicode = '\u2F4E', meanings = listOf("weapon"), strokes = 4),
        Ideogram(unicode = '\u2F4F', meanings = listOf("do not"), strokes = 4),

        Ideogram(unicode = '\u2F50', meanings = listOf("compare"), strokes = 4),
        Ideogram(unicode = '\u2F51', meanings = listOf("fur"), strokes = 4),
        Ideogram(unicode = '\u2F52', meanings = listOf("clan"), strokes = 4),
        Ideogram(unicode = '\u2F53', meanings = listOf("steam"), strokes = 4),
        Ideogram(unicode = '\u2F54', meanings = listOf("water"), strokes = 4),
        Ideogram(unicode = '\u2F55', meanings = listOf("fire"), strokes = 4, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F56', meanings = listOf("claw"), strokes = 4),
        Ideogram(unicode = '\u2F57', meanings = listOf("father"), strokes = 4),
        Ideogram(unicode = '\u2F58', meanings = listOf("double x"), strokes = 4),
        Ideogram(unicode = '\u2F59', meanings = listOf("half tree trunk"), strokes = 4),
        Ideogram(unicode = '\u2F5A', meanings = listOf("slice"), strokes = 4),
        Ideogram(unicode = '\u2F5B', meanings = listOf("fang"), strokes = 4),
        Ideogram(unicode = '\u2F5C', meanings = listOf("cow"), strokes = 4),
        Ideogram(unicode = '\u2F5D', meanings = listOf("dog"), strokes = 4, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F5E', meanings = listOf("profound"), strokes = 5),
        Ideogram(unicode = '\u2F5F', meanings = listOf("jade"), strokes = 4, decompositions = listOf('\u2F02')),

        Ideogram(unicode = '\u2F60', meanings = listOf("melon"), strokes = 6),
        Ideogram(unicode = '\u2F61', meanings = listOf("tile"), strokes = 5, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F62', meanings = listOf("sweet"), strokes = 5),
        Ideogram(unicode = '\u2F63', meanings = listOf("life"), strokes = 5),
        Ideogram(unicode = '\u2F64', meanings = listOf("use"), strokes = 5),
        Ideogram(unicode = '\u2F65', meanings = listOf("field"), strokes = 5),
        Ideogram(unicode = '\u2F66', meanings = listOf("bolt of cloth"), strokes = 5),
        Ideogram(unicode = '\u2F67', meanings = listOf("sickness"), strokes = 5),
        Ideogram(unicode = '\u2F68', meanings = listOf("dotted tent"), strokes = 5),
        Ideogram(unicode = '\u2F69', meanings = listOf("white"), strokes = 5),
        Ideogram(unicode = '\u2F6A', meanings = listOf("skin"), strokes = 5),
        Ideogram(unicode = '\u2F6B', meanings = listOf("dish"), strokes = 5),
        Ideogram(unicode = '\u2F6C', meanings = listOf("eye"), strokes = 5),
        Ideogram(unicode = '\u2F6D', meanings = listOf("spear"), strokes = 5),
        Ideogram(unicode = '\u2F6E', meanings = listOf("arrow"), strokes = 5),
        Ideogram(unicode = '\u2F6F', meanings = listOf("stone"), strokes = 5),

        Ideogram(unicode = '\u2F70', meanings = listOf("spirit"), strokes = 5, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F71', meanings = listOf("track"), strokes = 5),
        Ideogram(unicode = '\u2F72', meanings = listOf("grain"), strokes = 5),
        Ideogram(unicode = '\u2F73', meanings = listOf("cave"), strokes = 5),
        Ideogram(unicode = '\u2F74', meanings = listOf("stand"), strokes = 5),
        Ideogram(unicode = '\u2F75', meanings = listOf("bamboo"), strokes = 6),
        Ideogram(unicode = '\u2F76', meanings = listOf("rice"), strokes = 6),
        Ideogram(unicode = '\u2F77', meanings = listOf("silk"), strokes = 6, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F78', meanings = listOf("jar"), strokes = 6),
        Ideogram(unicode = '\u2F79', meanings = listOf("net"), strokes = 6),
        Ideogram(unicode = '\u2F7A', meanings = listOf("sheep"), strokes = 6),
        Ideogram(unicode = '\u2F7B', meanings = listOf("feather"), strokes = 6),
        Ideogram(unicode = '\u2F7C', meanings = listOf("old"), strokes = 6),
        Ideogram(unicode = '\u2F7D', meanings = listOf("and"), strokes = 6),
        Ideogram(unicode = '\u2F7E', meanings = listOf("plow"), strokes = 6),
        Ideogram(unicode = '\u2F7F', meanings = listOf("ear"), strokes = 6),

        Ideogram(unicode = '\u2F80', meanings = listOf("brush"), strokes = 6),
        Ideogram(unicode = '\u2F81', meanings = listOf("meat"), strokes = 6),
        Ideogram(unicode = '\u2F82', meanings = listOf("minister"), strokes = 7),
        Ideogram(unicode = '\u2F83', meanings = listOf("self"), strokes = 6),
        Ideogram(unicode = '\u2F84', meanings = listOf("arrive"), strokes = 6),
        Ideogram(unicode = '\u2F85', meanings = listOf("mortar"), strokes = 6),
        Ideogram(unicode = '\u2F86', meanings = listOf("tongue"), strokes = 6),
        Ideogram(unicode = '\u2F87', meanings = listOf("oppose"), strokes = 6),
        Ideogram(unicode = '\u2F88', meanings = listOf("boat"), strokes = 6),
        Ideogram(unicode = '\u2F89', meanings = listOf("stopping"), strokes = 6),
        Ideogram(unicode = '\u2F8A', meanings = listOf("color"), strokes = 6),
        Ideogram(unicode = '\u2F8B', meanings = listOf("grass"), strokes = 6),
        Ideogram(unicode = '\u2F8C', meanings = listOf("tiger"), strokes = 6),
        Ideogram(unicode = '\u2F8D', meanings = listOf("insect"), strokes = 6),
        Ideogram(unicode = '\u2F8E', meanings = listOf("blood"), strokes = 6),
        Ideogram(unicode = '\u2F8F', meanings = listOf("walk enclosure"), strokes = 6),

        Ideogram(unicode = '\u2F90', meanings = listOf("clothes"), strokes = 6),
        Ideogram(unicode = '\u2F91', meanings = listOf("west"), strokes = 6),
        Ideogram(unicode = '\u2F92', meanings = listOf("see"), strokes = 7),
        Ideogram(unicode = '\u2F93', meanings = listOf("horn"), strokes = 7),
        Ideogram(unicode = '\u2F94', meanings = listOf("speech"), strokes = 7),
        Ideogram(unicode = '\u2F95', meanings = listOf("valley"), strokes = 7),
        Ideogram(unicode = '\u2F96', meanings = listOf("bean"), strokes = 7),
        Ideogram(unicode = '\u2F97', meanings = listOf("pig"), strokes = 7),
        Ideogram(unicode = '\u2F98', meanings = listOf("badger"), strokes = 7),
        Ideogram(unicode = '\u2F99', meanings = listOf("shell"), strokes = 7),
        Ideogram(unicode = '\u2F9A', meanings = listOf("red"), strokes = 7, decompositions = listOf('\u2F02')),
        Ideogram(unicode = '\u2F9B', meanings = listOf("run"), strokes = 7),
        Ideogram(unicode = '\u2F9C', meanings = listOf("foot"), strokes = 7),
        Ideogram(unicode = '\u2F9D', meanings = listOf("body"), strokes = 7),
        Ideogram(unicode = '\u2F9E', meanings = listOf("cart"), strokes = 7),
        Ideogram(unicode = '\u2F9F', meanings = listOf("bitter"), strokes = 7),

        Ideogram(unicode = '\u2FA0', meanings = listOf("morning"), strokes = 7),
        Ideogram(unicode = '\u2FA1', meanings = listOf("walk"), strokes = 3),
        Ideogram(unicode = '\u2FA2', meanings = listOf("city"), strokes = 7),
        Ideogram(unicode = '\u2FA3', meanings = listOf("wine"), strokes = 7),
        Ideogram(unicode = '\u2FA4', meanings = listOf("distinguish"), strokes = 7),
        Ideogram(unicode = '\u2FA5', meanings = listOf("village"), strokes = 7),
        Ideogram(unicode = '\u2FA6', meanings = listOf("gold"), strokes = 8),
        Ideogram(unicode = '\u2FA7', meanings = listOf("long"), strokes = 8),
        Ideogram(unicode = '\u2FA8', meanings = listOf("gate"), strokes = 8),
        Ideogram(unicode = '\u2FA9', meanings = listOf("mound"), strokes = 3),
        Ideogram(unicode = '\u2FAA', meanings = listOf("slave"), strokes = 8),
        Ideogram(unicode = '\u2FAB', meanings = listOf("short tailed bird"), strokes = 8),
        Ideogram(unicode = '\u2FAC', meanings = listOf("rain"), strokes = 8),
        Ideogram(unicode = '\u2FAD', meanings = listOf("blue"), strokes = 8),
        Ideogram(unicode = '\u2FAE', meanings = listOf("wrong"), strokes = 8),
        Ideogram(unicode = '\u2FAF', meanings = listOf("face"), strokes = 9),

        Ideogram(unicode = '\u2FB0', meanings = listOf("leather"), strokes = 9),
        Ideogram(unicode = '\u2FB1', meanings = listOf("tanned leather"), strokes = 10),
        Ideogram(unicode = '\u2FB2', meanings = listOf("leek"), strokes = 9),
        Ideogram(unicode = '\u2FB3', meanings = listOf("sound"), strokes = 9),
        Ideogram(unicode = '\u2FB4', meanings = listOf("leaf"), strokes = 9),
        Ideogram(unicode = '\u2FB5', meanings = listOf("wind"), strokes = 9),
        Ideogram(unicode = '\u2FB6', meanings = listOf("fly"), strokes = 9),
        Ideogram(unicode = '\u2FB7', meanings = listOf("eat"), strokes = 9),
        Ideogram(unicode = '\u2FB8', meanings = listOf("head"), strokes = 9),
        Ideogram(unicode = '\u2FB9', meanings = listOf("fragrant"), strokes = 9),
        Ideogram(unicode = '\u2FBA', meanings = listOf("horse"), strokes = 10),
        Ideogram(unicode = '\u2FBB', meanings = listOf("bone"), strokes = 10),
        Ideogram(unicode = '\u2FBC', meanings = listOf("tall"), strokes = 10),
        Ideogram(unicode = '\u2FBD', meanings = listOf("hair"), strokes = 10),
        Ideogram(unicode = '\u2FBE', meanings = listOf("fight"), strokes = 10),
        Ideogram(unicode = '\u2FBF', meanings = listOf("sacrificial wine"), strokes = 10),

        Ideogram(unicode = '\u2FC0', meanings = listOf("cauldron"), strokes = 10),
        Ideogram(unicode = '\u2FC1', meanings = listOf("ghost"), strokes = 10),
        Ideogram(unicode = '\u2FC2', meanings = listOf("fish"), strokes = 11),
        Ideogram(unicode = '\u2FC3', meanings = listOf("bird"), strokes = 11),
        Ideogram(unicode = '\u2FC4', meanings = listOf("salt"), strokes = 11),
        Ideogram(unicode = '\u2FC5', meanings = listOf("deer"), strokes = 11),
        Ideogram(unicode = '\u2FC6', meanings = listOf("wheat"), strokes = 11),
        Ideogram(unicode = '\u2FC7', meanings = listOf("hemp"), strokes = 11),
        Ideogram(unicode = '\u2FC8', meanings = listOf("yellow"), strokes = 12),
        Ideogram(unicode = '\u2FC9', meanings = listOf("millet"), strokes = 12),
        Ideogram(unicode = '\u2FCA', meanings = listOf("black"), strokes = 12),
        Ideogram(unicode = '\u2FCB', meanings = listOf("embroidery"), strokes = 12),
        Ideogram(unicode = '\u2FCC', meanings = listOf("frog"), strokes = 13),
        Ideogram(unicode = '\u2FCD', meanings = listOf("tripod"), strokes = 13),
        Ideogram(unicode = '\u2FCE', meanings = listOf("drum"), strokes = 13),
        Ideogram(unicode = '\u2FCF', meanings = listOf("rat"), strokes = 13),

        Ideogram(unicode = '\u2FD0', meanings = listOf("nose"), strokes = 14),
        Ideogram(unicode = '\u2FD1', meanings = listOf("even"), strokes = 14),
        Ideogram(unicode = '\u2FD2', meanings = listOf("tooth"), strokes = 15),
        Ideogram(unicode = '\u2FD3', meanings = listOf("dragon"), strokes = 16),
        Ideogram(unicode = '\u2FD4', meanings = listOf("turtle"), strokes = 16),
        Ideogram(unicode = '\u2FD5', meanings = listOf("flute"), strokes = 17),
        )
}