package com.example.kanjimemorized

import com.example.kanjimemorized.data.Ideogram
import javax.inject.Singleton

object IdeogramData {
    @Singleton
    val IdeogramData: Array<Ideogram> = arrayOf(
/*https://www.kanjidamage.com/kanji*/
        Ideogram(unicode = '\u4E00', meanings = listOf("one"), strokes = 1),
        Ideogram(unicode = '\u4E59', meanings = listOf("second"), strokes = 1),

        Ideogram(unicode = '\u4EBA', meanings = listOf("man", "person"), strokes = 2),
        Ideogram(unicode = '\u5341', meanings = listOf("ten"), strokes = 2, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u4E8C', meanings = listOf("two"), strokes = 2, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u4E5D', meanings = listOf("nine"), strokes = 2),
        Ideogram(unicode = '\u5165', meanings = listOf("enter", "insert"), strokes = 2),
        Ideogram(unicode = '\u516B', meanings = listOf("eight"), strokes = 2),
        Ideogram(unicode = '\u4E03', meanings = listOf("seven"), strokes = 2, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u529B', meanings = listOf("power","strength"), strokes = 2),

        Ideogram(unicode = '\u5200', meanings = listOf("knife", "sword"), strokes = 2),

        Ideogram(unicode = '\u4E01', meanings = listOf("street"), strokes = 2, decompositions = listOf('\u4E00')),

        Ideogram(unicode = '\u4E86', meanings = listOf("complete", "finish"), strokes = 2),
        Ideogram(unicode = '\u53C8', meanings = listOf("again"), strokes = 2),

        Ideogram(unicode = '\u5927', meanings = listOf("big"), strokes = 3, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u4E09', meanings = listOf("three"), strokes = 3, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u4E0A', meanings = listOf("above", "up"), strokes = 3, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u5B50', meanings = listOf("child"), strokes = 3, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u4E0B', meanings = listOf("below", "down"), strokes = 3, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u5C0F', meanings = listOf("small"), strokes = 3),
        Ideogram(unicode = '\u5C71', meanings = listOf("mountain"), strokes = 3),
        Ideogram(unicode = '\u5973', meanings = listOf("woman"), strokes = 3, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u5DDD', meanings = listOf("river"), strokes = 3),
        Ideogram(unicode = '\u5343', meanings = listOf("thousand"), strokes = 3, decompositions = listOf('\u5341')),
        Ideogram(unicode = '\u571F', meanings = listOf("earth"), strokes = 3, decompositions = listOf('\u4E00', '\u5341')),
        Ideogram(unicode = '\u53E3', meanings = listOf("mouth"), strokes = 3),
        Ideogram(unicode = '\u5915', meanings = listOf("evening"), strokes = 3),

        Ideogram(unicode = '\u4E07', meanings = listOf("ten thousand"), strokes = 3, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u5DE5', meanings = listOf("craft"), strokes = 3),
        Ideogram(unicode = '\u624D', meanings = listOf("genius"), strokes = 3),
        Ideogram(unicode = '\u4E38', meanings = listOf("round"), strokes = 3, decompositions = listOf('\u4E5D')),
        Ideogram(unicode = '\u5F13', meanings = listOf("bow"), strokes = 3),

        Ideogram(unicode = '\u4E45', meanings = listOf("long time", "old story"), strokes = 3),
        Ideogram(unicode = '\u58EB', meanings = listOf("scholar", "samurai"), strokes = 3),

        Ideogram(unicode = '\u4EA1', meanings = listOf("deceased"), strokes = 3),
        Ideogram(unicode = '\u5E72', meanings = listOf("dry"), strokes = 3, decompositions = listOf('\u5341')),
        Ideogram(unicode = '\u5DF1', meanings = listOf("oneself"), strokes = 3),
        Ideogram(unicode = '\u5BF8', meanings = listOf("inch"), strokes = 3),

        Ideogram(unicode = '\u4E0E', meanings = listOf("give, bestow"), strokes = 3, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u53CA', meanings = listOf("reach out", "exert"), strokes = 3, decompositions = listOf('\u53C8')),
        Ideogram(unicode = '\u4E08', meanings = listOf("length", "measure"), strokes = 3, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u51E1', meanings = listOf("commonplace", "ordinary"), strokes = 3),

        Ideogram(unicode = '\u5203', meanings = listOf("blade", "sword"), strokes = 3, decompositions = listOf('\u5200')),

        Ideogram(unicode = '\u5DFE', meanings = listOf("towel"), strokes = 3),
        Ideogram(unicode = '\u4E5E', meanings = listOf("beg"), strokes = 3, decompositions = listOf('\u4E59')),

        Ideogram(unicode = '\u65E5', meanings = listOf("day", "sun"), strokes = 4),
        Ideogram(unicode = '\u4E2D', meanings = listOf("inside", "middle"), strokes = 4, decompositions = listOf('\u53E3')),
        Ideogram(unicode = '\u6708', meanings = listOf("month", "moon"), strokes = 4),
        Ideogram(unicode = '\u5E94', meanings = listOf("five"), strokes = 4, decompositions = listOf('\u4E8C')),
        Ideogram(unicode = '\u5186', meanings = listOf("circle", "yen"), strokes = 4),
        Ideogram(unicode = '\u516D', meanings = listOf("six"), strokes = 4, decompositions = listOf('\u516B')),
        Ideogram(unicode = '\u6C34', meanings = listOf("water"), strokes = 4),
        Ideogram(unicode = '\u6728', meanings = listOf("tree", "wood"), strokes = 4),
        Ideogram(unicode = '\u5929', meanings = listOf("heavens", "sky"), strokes = 4, decompositions = listOf('\u4E00', '\u5927')),
        Ideogram(unicode = '\u706B', meanings = listOf("fire"), strokes = 4),
        Ideogram(unicode = '\u624B', meanings = listOf("hand"), strokes = 4),
        Ideogram(unicode = '\u6587', meanings = listOf("sentence", "literature"), strokes = 4),
        Ideogram(unicode = '\u72AC', meanings = listOf("dog"), strokes = 4, decompositions = listOf('\u5927')),
        Ideogram(unicode = '\u738B', meanings = listOf("king"), strokes = 4),

        Ideogram(unicode = '\u5206', meanings = listOf("part", "minute"), strokes = 4, decompositions = listOf('\u5200', '\u516B')),
        Ideogram(unicode = '\u4ECA', meanings = listOf("now"), strokes = 4, decompositions = listOf('\u4EBA')),
        Ideogram(unicode = '\u5348', meanings = listOf("noon"), strokes = 4, decompositions = listOf('\u5E72')),
        Ideogram(unicode = '\u53CB', meanings = listOf("friend"), strokes = 4, decompositions = listOf('\u53C8')),
        Ideogram(unicode = '\u7236', meanings = listOf("father"), strokes = 4),
        Ideogram(unicode = '\u5C11', meanings = listOf("few", "little"), strokes = 4, decompositions = listOf('\u5C0F')),
        Ideogram(unicode = '\u65B9', meanings = listOf("direction"), strokes = 4),
        Ideogram(unicode = '\u5FC3', meanings = listOf("heart", "mind", "spirit"), strokes = 4),
        Ideogram(unicode = '\u5143', meanings = listOf("beginning"), strokes = 4, decompositions = listOf('\u513F', '\u4E8C')),
        Ideogram(unicode = '\u6B62', meanings = listOf("stop"), strokes = 4),
        Ideogram(unicode = '\u5207', meanings = listOf("cut"), strokes = 4, decompositions = listOf('\u5200')),
        Ideogram(unicode = '\u725B', meanings = listOf("cow"), strokes = 4),
        Ideogram(unicode = '\u516C', meanings = listOf("public"), strokes = 4, decompositions = listOf('\u516B')),
        Ideogram(unicode = '\u5f15', meanings = listOf("pull"), strokes = 4),
        Ideogram(unicode = '\u592A', meanings = listOf("plump"), strokes = 4, decompositions = listOf('\u5927')),
        Ideogram(unicode = '\u5185', meanings = listOf("inside", "within"), strokes = 4, decompositions = listOf('\u53E3')),
        Ideogram(unicode = '\u6238', meanings = listOf("door"), strokes = 4),
        Ideogram(unicode = '\u6BDB', meanings = listOf("fur", "hair"), strokes = 4),

        Ideogram(unicode = '\u5316', meanings = listOf("change"), strokes = 4),
        Ideogram(unicode = '\u4E88', meanings = listOf("beforehand", "previous"), strokes = 4),
        Ideogram(unicode = '\u53CD', meanings = listOf("anti-"), strokes = 4, decompositions = listOf('\u53C8')),
        Ideogram(unicode = '\u533A', meanings = listOf("ward", "district"), strokes = 4),

        Ideogram(unicode = '\u4E0D', meanings = listOf("negative"), strokes = 4, decompositions = listOf('\u4E00')),
        Ideogram(unicode = '\u592B', meanings = listOf("husband", "man"), strokes = 4, decompositions = listOf('\u5927')),
        Ideogram(unicode = '\u6B20', meanings = listOf("lack"), strokes = 4),
        Ideogram(unicode = '\u6C0F', meanings = listOf("family name", "surname"), strokes = 4),
        Ideogram(unicode = '\u4E95', meanings = listOf("water well"), strokes = 4),

        Ideogram(unicode = '\u652F', meanings = listOf("branch", "support"), strokes = 4, decompositions = listOf('\u5341', '\u53C8')),
        Ideogram(unicode = '\u6BD4', meanings = listOf("compare"), strokes = 4),
        Ideogram(unicode = '\u4ECF', meanings = listOf("Buddha"), strokes = 4),

        Ideogram(unicode = '\u4E92', meanings = listOf("mutually"), strokes = 4, decompositions = listOf('\u4E8C')),
        Ideogram(unicode = '\u4ECB', meanings = listOf("mediate"), strokes = 4, decompositions = listOf('\u4EBA')),
        Ideogram(unicode = '\u5339', meanings = listOf("equal", "head"), strokes = 4),
        Ideogram(unicode = '\u4E39', meanings = listOf("rust-colored", "red lead"), strokes = 4),
        Ideogram(unicode = '\u51F6', meanings = listOf("villain", "evil"), strokes = 4),
        Ideogram(unicode = '\u5208', meanings = listOf("reap", "cut"), strokes = 4),

        Ideogram(unicode = '\u53CC', meanings = listOf("pair", "set"), strokes = 4, decompositions = listOf('\u53C8')),
        Ideogram(unicode = '\u5E7B', meanings = listOf("phantasm"), strokes = 4),
        Ideogram(unicode = '\u4E4F', meanings = listOf("destitution"), strokes = 4),
        Ideogram(unicode = '\u5197', meanings = listOf("superfluous"), strokes = 4),
        Ideogram(unicode = '\u6597', meanings = listOf("Big Dipper"), strokes = 4),
        Ideogram(unicode = '\u5B54', meanings = listOf("cavity"), strokes = 4, decompositions = listOf('\u5B50', '\u4E59')),
        Ideogram(unicode = '\u65A4', meanings = listOf("axe"), strokes = 4),

        Ideogram(unicode = '\u5F14', meanings = listOf("condolences", "morning"), strokes = 4),
        Ideogram(unicode = '\u5C6F', meanings = listOf("barracks"), strokes = 4),
        Ideogram(unicode = '\u5347', meanings = listOf("measuring box"), strokes = 4),
        Ideogram(unicode = '\u5384', meanings = listOf("unlucky"), strokes = 4),

        Ideogram(unicode = '\u7259', meanings = listOf("tusk", "fang"), strokes = 4),
        Ideogram(unicode = '\u52FE', meanings = listOf("be bent", "slope"), strokes = 4),
        Ideogram(unicode = '\u722A', meanings = listOf("claw"), strokes = 4),
        Ideogram(unicode = '\u722A', meanings = listOf("fragrant", "glow"), strokes = 4),


//        Ideogram(unicode = '\u2F5E', meanings = listOf("profound"), strokes = 5),
//
//        Ideogram(unicode = '\u2F60', meanings = listOf("melon"), strokes = 6),
//        Ideogram(unicode = '\u2F61', meanings = listOf("tile"), strokes = 5, decompositions = listOf('\u2F02')),
//        Ideogram(unicode = '\u2F62', meanings = listOf("sweet"), strokes = 5),
//        Ideogram(unicode = '\u2F63', meanings = listOf("life"), strokes = 5),
//        Ideogram(unicode = '\u2F64', meanings = listOf("use"), strokes = 5),
//        Ideogram(unicode = '\u2F65', meanings = listOf("field"), strokes = 5),
//        Ideogram(unicode = '\u2F66', meanings = listOf("bolt of cloth"), strokes = 5),
//        Ideogram(unicode = '\u2F67', meanings = listOf("sickness"), strokes = 5),
//        Ideogram(unicode = '\u2F68', meanings = listOf("dotted tent"), strokes = 5),
//        Ideogram(unicode = '\u2F69', meanings = listOf("white"), strokes = 5),
//        Ideogram(unicode = '\u2F6A', meanings = listOf("skin"), strokes = 5),
//        Ideogram(unicode = '\u2F6B', meanings = listOf("dish"), strokes = 5),
//        Ideogram(unicode = '\u2F6C', meanings = listOf("eye"), strokes = 5),
//        Ideogram(unicode = '\u2F6D', meanings = listOf("spear"), strokes = 5),
//        Ideogram(unicode = '\u2F6E', meanings = listOf("arrow"), strokes = 5),
//        Ideogram(unicode = '\u2F6F', meanings = listOf("stone"), strokes = 5),
//
//        Ideogram(unicode = '\u2F70', meanings = listOf("spirit"), strokes = 5, decompositions = listOf('\u2F02')),
//        Ideogram(unicode = '\u2F71', meanings = listOf("track"), strokes = 5),
//        Ideogram(unicode = '\u2F72', meanings = listOf("grain"), strokes = 5),
//        Ideogram(unicode = '\u2F73', meanings = listOf("cave"), strokes = 5),
//        Ideogram(unicode = '\u2F74', meanings = listOf("stand"), strokes = 5),
//        Ideogram(unicode = '\u2F75', meanings = listOf("bamboo"), strokes = 6),
//        Ideogram(unicode = '\u2F76', meanings = listOf("rice"), strokes = 6),
//        Ideogram(unicode = '\u2F77', meanings = listOf("silk"), strokes = 6, decompositions = listOf('\u2F02')),
//        Ideogram(unicode = '\u2F78', meanings = listOf("jar"), strokes = 6),
//        Ideogram(unicode = '\u2F79', meanings = listOf("net"), strokes = 6),
//        Ideogram(unicode = '\u2F7A', meanings = listOf("sheep"), strokes = 6),
//        Ideogram(unicode = '\u2F7B', meanings = listOf("feather"), strokes = 6),
//        Ideogram(unicode = '\u2F7C', meanings = listOf("old"), strokes = 6),
//        Ideogram(unicode = '\u2F7D', meanings = listOf("and"), strokes = 6),
//        Ideogram(unicode = '\u2F7E', meanings = listOf("plow"), strokes = 6),
//        Ideogram(unicode = '\u2F7F', meanings = listOf("ear"), strokes = 6),
//
//        Ideogram(unicode = '\u2F80', meanings = listOf("brush"), strokes = 6),
//        Ideogram(unicode = '\u2F81', meanings = listOf("meat"), strokes = 6),
//        Ideogram(unicode = '\u2F82', meanings = listOf("minister"), strokes = 7),
//        Ideogram(unicode = '\u2F83', meanings = listOf("self"), strokes = 6),
//        Ideogram(unicode = '\u2F84', meanings = listOf("arrive"), strokes = 6),
//        Ideogram(unicode = '\u2F85', meanings = listOf("mortar"), strokes = 6),
//        Ideogram(unicode = '\u2F86', meanings = listOf("tongue"), strokes = 6),
//        Ideogram(unicode = '\u2F87', meanings = listOf("oppose"), strokes = 6),
//        Ideogram(unicode = '\u2F88', meanings = listOf("boat"), strokes = 6),
//        Ideogram(unicode = '\u2F89', meanings = listOf("stopping"), strokes = 6),
//        Ideogram(unicode = '\u2F8A', meanings = listOf("color"), strokes = 6),
//        Ideogram(unicode = '\u2F8B', meanings = listOf("grass"), strokes = 6),
//        Ideogram(unicode = '\u2F8C', meanings = listOf("tiger"), strokes = 6),
//        Ideogram(unicode = '\u2F8D', meanings = listOf("insect"), strokes = 6),
//        Ideogram(unicode = '\u2F8E', meanings = listOf("blood"), strokes = 6),
//        Ideogram(unicode = '\u2F8F', meanings = listOf("walk enclosure"), strokes = 6),
//
//        Ideogram(unicode = '\u2F90', meanings = listOf("clothes"), strokes = 6),
//        Ideogram(unicode = '\u2F91', meanings = listOf("west"), strokes = 6),
//        Ideogram(unicode = '\u2F92', meanings = listOf("see"), strokes = 7),
//        Ideogram(unicode = '\u2F93', meanings = listOf("horn"), strokes = 7),
//        Ideogram(unicode = '\u2F94', meanings = listOf("speech"), strokes = 7),
//        Ideogram(unicode = '\u2F95', meanings = listOf("valley"), strokes = 7),
//        Ideogram(unicode = '\u2F96', meanings = listOf("bean"), strokes = 7),
//        Ideogram(unicode = '\u2F97', meanings = listOf("pig"), strokes = 7),
//        Ideogram(unicode = '\u2F98', meanings = listOf("badger"), strokes = 7),
//        Ideogram(unicode = '\u2F99', meanings = listOf("shell"), strokes = 7),
//        Ideogram(unicode = '\u2F9A', meanings = listOf("red"), strokes = 7, decompositions = listOf('\u2F02')),
//        Ideogram(unicode = '\u2F9B', meanings = listOf("run"), strokes = 7),
//        Ideogram(unicode = '\u2F9C', meanings = listOf("foot"), strokes = 7),
//        Ideogram(unicode = '\u2F9D', meanings = listOf("body"), strokes = 7),
//        Ideogram(unicode = '\u2F9E', meanings = listOf("cart"), strokes = 7),
//        Ideogram(unicode = '\u2F9F', meanings = listOf("bitter"), strokes = 7),
//
//        Ideogram(unicode = '\u2FA0', meanings = listOf("morning"), strokes = 7),
//        Ideogram(unicode = '\u2FA1', meanings = listOf("walk"), strokes = 3),
//        Ideogram(unicode = '\u2FA2', meanings = listOf("city"), strokes = 7),
//        Ideogram(unicode = '\u2FA3', meanings = listOf("wine"), strokes = 7),
//        Ideogram(unicode = '\u2FA4', meanings = listOf("distinguish"), strokes = 7),
//        Ideogram(unicode = '\u2FA5', meanings = listOf("village"), strokes = 7),
//        Ideogram(unicode = '\u2FA6', meanings = listOf("gold"), strokes = 8),
//        Ideogram(unicode = '\u2FA7', meanings = listOf("long"), strokes = 8),
//        Ideogram(unicode = '\u2FA8', meanings = listOf("gate"), strokes = 8),
//        Ideogram(unicode = '\u2FA9', meanings = listOf("mound"), strokes = 3),
//        Ideogram(unicode = '\u2FAA', meanings = listOf("slave"), strokes = 8),
//        Ideogram(unicode = '\u2FAB', meanings = listOf("short tailed bird"), strokes = 8),
//        Ideogram(unicode = '\u2FAC', meanings = listOf("rain"), strokes = 8),
//        Ideogram(unicode = '\u2FAD', meanings = listOf("blue"), strokes = 8),
//        Ideogram(unicode = '\u2FAE', meanings = listOf("wrong"), strokes = 8),
//        Ideogram(unicode = '\u2FAF', meanings = listOf("face"), strokes = 9),
//
//        Ideogram(unicode = '\u2FB0', meanings = listOf("leather"), strokes = 9),
//        Ideogram(unicode = '\u2FB1', meanings = listOf("tanned leather"), strokes = 10),
//        Ideogram(unicode = '\u2FB2', meanings = listOf("leek"), strokes = 9),
//        Ideogram(unicode = '\u2FB3', meanings = listOf("sound"), strokes = 9),
//        Ideogram(unicode = '\u2FB4', meanings = listOf("leaf"), strokes = 9),
//        Ideogram(unicode = '\u2FB5', meanings = listOf("wind"), strokes = 9),
//        Ideogram(unicode = '\u2FB6', meanings = listOf("fly"), strokes = 9),
//        Ideogram(unicode = '\u2FB7', meanings = listOf("eat"), strokes = 9),
//        Ideogram(unicode = '\u2FB8', meanings = listOf("head"), strokes = 9),
//        Ideogram(unicode = '\u2FB9', meanings = listOf("fragrant"), strokes = 9),
//        Ideogram(unicode = '\u2FBA', meanings = listOf("horse"), strokes = 10),
//        Ideogram(unicode = '\u2FBB', meanings = listOf("bone"), strokes = 10),
//        Ideogram(unicode = '\u2FBC', meanings = listOf("tall"), strokes = 10),
//        Ideogram(unicode = '\u2FBD', meanings = listOf("hair"), strokes = 10),
//        Ideogram(unicode = '\u2FBE', meanings = listOf("fight"), strokes = 10),
//        Ideogram(unicode = '\u2FBF', meanings = listOf("sacrificial wine"), strokes = 10),
//
//        Ideogram(unicode = '\u2FC0', meanings = listOf("cauldron"), strokes = 10),
//        Ideogram(unicode = '\u2FC1', meanings = listOf("ghost"), strokes = 10),
//        Ideogram(unicode = '\u2FC2', meanings = listOf("fish"), strokes = 11),
//        Ideogram(unicode = '\u2FC3', meanings = listOf("bird"), strokes = 11),
//        Ideogram(unicode = '\u2FC4', meanings = listOf("salt"), strokes = 11),
//        Ideogram(unicode = '\u2FC5', meanings = listOf("deer"), strokes = 11),
//        Ideogram(unicode = '\u2FC6', meanings = listOf("wheat"), strokes = 11),
//        Ideogram(unicode = '\u2FC7', meanings = listOf("hemp"), strokes = 11),
//        Ideogram(unicode = '\u2FC8', meanings = listOf("yellow"), strokes = 12),
//        Ideogram(unicode = '\u2FC9', meanings = listOf("millet"), strokes = 12),
//        Ideogram(unicode = '\u2FCA', meanings = listOf("black"), strokes = 12),
//        Ideogram(unicode = '\u2FCB', meanings = listOf("embroidery"), strokes = 12),
//        Ideogram(unicode = '\u2FCC', meanings = listOf("frog"), strokes = 13),
//        Ideogram(unicode = '\u2FCD', meanings = listOf("tripod"), strokes = 13),
//        Ideogram(unicode = '\u2FCE', meanings = listOf("drum"), strokes = 13),
//        Ideogram(unicode = '\u2FCF', meanings = listOf("rat"), strokes = 13),
//
//        Ideogram(unicode = '\u2FD0', meanings = listOf("nose"), strokes = 14),
//        Ideogram(unicode = '\u2FD1', meanings = listOf("even"), strokes = 14),
//        Ideogram(unicode = '\u2FD2', meanings = listOf("tooth"), strokes = 15),
//        Ideogram(unicode = '\u2FD3', meanings = listOf("dragon"), strokes = 16),
//        Ideogram(unicode = '\u2FD4', meanings = listOf("turtle"), strokes = 16),
//        Ideogram(unicode = '\u2FD5', meanings = listOf("flute"), strokes = 17),
        )
}